### ISSUE TITLE
Doxygen header data for parameters is incorrect

### ISSUE THREAD

**Issue by gigapod** [sparkfun/SparkFun_Toolkit#35]
Here: https://github.com/sparkfun/SparkFun_Toolkit/blob/3ac4a2c8bf415dcc198f2975f7beb11745daaee1/src/sfeTk/sfeTkIBus.h#L119

This is a copy paste issue . The length parameter missing, the register parameter isn't part of this interface. 

This shows up in the generated documentation of the library here:
https://docs.sparkfun.com/SparkFun_Toolkit/classsfe_tk_i_bus.html#a6d0b67b13da3bde605b5a030ca5d4c33

**Comment by edspark** [comment]
Fixed [here](https://github.com/sparkfun/SparkFun_Toolkit/commit/97a2ab150fb8b829f2e3ef939ac56ac8c0c99d73)
